name = "Showcase"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
GetDP = "dbfd83e6-7aba-450b-9c2b-93ccd973023a"
LineCableModels = "dffb7669-8cd4-4628-99dd-7694e356ba37"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
PlutoStyles = "16e07271-a41c-4e3e-b73a-b807cf2ea0eb"

[sources]
GetDP = {rev = "main", url = "https://github.com/Electa-Git/GetDP.jl"}
LineCableModels = {path = ".."}


[compat]
julia = "1.11"
